### Create a user
POST http://localhost:4500/api/users/
Content-Type: application/json

{
  "nom": "John",
  "prenom" : "Doe",
  "date_de_naissance" : "2004-02-12",
  "email": "johndoe@example.com",
  "mot_de_passe": "securepassword"
}
