name: Update Dependencies

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch (or replace with your target branch)

jobs:
  update-dependencies:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.8'  # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update requirements.txt
        run: |
          pip freeze > requirements.txt

      - name: Commit and push updated requirements.txt
        uses: EndBug/add-and-commit@v7
        with:
          author_name: 'GitHub Actions'
          author_email: 'github-actions@github.com'
          message: 'Update requirements.txt with latest dependencies'
